[tool.poetry]
name = "mothership"
version = "0.1.0"
description = ""
authors = ["Gyanendra Mishra <anomaly.the@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.9"
streamlit = "^1.32.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
