"""empty message

Revision ID: 26fd41debd46
Revises: a1fd7486141b
Create Date: 2024-06-23 13:47:39.030385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "26fd41debd46"
down_revision = "a1fd7486141b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bot", schema=None) as batch_op:
        batch_op.add_column(sa.Column("suffix", sa.String(length=12), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bot", schema=None) as batch_op:
        batch_op.drop_column("suffix")

    # ### end Alembic commands ###
